//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackendForCompany.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BackendForCompany.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have attempted to input incorrect password. Your account is lock for 30 minutes..
        /// </summary>
        internal static string accountLock30MinMsg {
            get {
                return ResourceManager.GetString("accountLock30MinMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is locked. Please login again later..
        /// </summary>
        internal static string accountLockedMsg {
            get {
                return ResourceManager.GetString("accountLockedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account does not exist..
        /// </summary>
        internal static string accountNotExistMsg {
            get {
                return ResourceManager.GetString("accountNotExistMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap add {
            get {
                object obj = ResourceManager.GetObject("add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new report successsfully.
        /// </summary>
        internal static string addNewReportSuccessMsg {
            get {
                return ResourceManager.GetString("addNewReportSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Successfully.
        /// </summary>
        internal static string addSuccessMsg {
            get {
                return ResourceManager.GetString("addSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap alert {
            get {
                object obj = ResourceManager.GetObject("alert", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string allText {
            get {
                return ResourceManager.GetString("allText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid amount has been refunded.
        /// </summary>
        internal static string amountRefundedMsg {
            get {
                return ResourceManager.GetString("amountRefundedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apporved by.
        /// </summary>
        internal static string apporvedBy1Text {
            get {
                return ResourceManager.GetString("apporvedBy1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string apporvedBy2Text {
            get {
                return ResourceManager.GetString("apporvedBy2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval Order.
        /// </summary>
        internal static string approvalOrderText {
            get {
                return ResourceManager.GetString("approvalOrderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap approve {
            get {
                object obj = ResourceManager.GetObject("approve", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to add a new report?
        ///(After adding, you cannot modify.).
        /// </summary>
        internal static string askAddReportDialogbox {
            get {
                return ResourceManager.GetString("askAddReportDialogbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to add a new report?
        ///(After adding, you cannot modify except return date.).
        /// </summary>
        internal static string askAddReportExceptReturnDateDialogbox {
            get {
                return ResourceManager.GetString("askAddReportExceptReturnDateDialogbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to logout the System?.
        /// </summary>
        internal static string askLogoutDialogbox {
            get {
                return ResourceManager.GetString("askLogoutDialogbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to record the return date?
        ///(After record, you cannot modify.).
        /// </summary>
        internal static string askRecordReturnDateDialogbox {
            get {
                return ResourceManager.GetString("askRecordReturnDateDialogbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention.
        /// </summary>
        internal static string attentionText {
            get {
                return ResourceManager.GetString("attentionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base.
        /// </summary>
        internal static string BaseText {
            get {
                return ResourceManager.GetString("BaseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottle.
        /// </summary>
        internal static string bottleText {
            get {
                return ResourceManager.GetString("bottleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        internal static string confirmationText {
            get {
                return ResourceManager.GetString("confirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap customer {
            get {
                object obj = ResourceManager.GetObject("customer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account(s) has/have been deleted..
        /// </summary>
        internal static string deleteAccountMsg {
            get {
                return ResourceManager.GetString("deleteAccountMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you delete account(s)?.
        /// </summary>
        internal static string deleteAccountYesNoMsg {
            get {
                return ResourceManager.GetString("deleteAccountYesNoMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted account(s) has/have been recovered..
        /// </summary>
        internal static string deletedAccountRecoverMsg {
            get {
                return ResourceManager.GetString("deletedAccountRecoverMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount have been deleted..
        /// </summary>
        internal static string deleteDiscountMsg {
            get {
                return ResourceManager.GetString("deleteDiscountMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you delete discount?.
        /// </summary>
        internal static string deleteDiscountYesNoMsg {
            get {
                return ResourceManager.GetString("deleteDiscountYesNoMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The notice has been deleted..
        /// </summary>
        internal static string deleteNoticeMsg {
            get {
                return ResourceManager.GetString("deleteNoticeMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you delete notice?.
        /// </summary>
        internal static string deleteNoticeYesNoMsg {
            get {
                return ResourceManager.GetString("deleteNoticeYesNoMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account(s) has/have been deleted permanently..
        /// </summary>
        internal static string deletePermanentlyAccountMsg {
            get {
                return ResourceManager.GetString("deletePermanentlyAccountMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you delete account(s) permanently?.
        /// </summary>
        internal static string deletePermanentlyAccountYesNoMsg {
            get {
                return ResourceManager.GetString("deletePermanentlyAccountYesNoMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string deleteTitle {
            get {
                return ResourceManager.GetString("deleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap discount {
            get {
                object obj = ResourceManager.GetObject("discount", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email exists.
        /// </summary>
        internal static string emailExists {
            get {
                return ResourceManager.GetString("emailExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string errorText {
            get {
                return ResourceManager.GetString("errorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Express package has been opened/damaged.
        /// </summary>
        internal static string expressPackageDamaged {
            get {
                return ResourceManager.GetString("expressPackageDamaged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get status.
        /// </summary>
        internal static string failGetPaymentStatusMsg {
            get {
                return ResourceManager.GetString("failGetPaymentStatusMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to refund.
        /// </summary>
        internal static string failRefundMsg {
            get {
                return ResourceManager.GetString("failRefundMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to add.
        /// </summary>
        internal static string failToAddMsg {
            get {
                return ResourceManager.GetString("failToAddMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to change password..
        /// </summary>
        internal static string failToChangePasswdMsg {
            get {
                return ResourceManager.GetString("failToChangePasswdMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send email.
        /// </summary>
        internal static string failToSendMailMsg {
            get {
                return ResourceManager.GetString("failToSendMailMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update.
        /// </summary>
        internal static string failToUpdateMsg {
            get {
                return ResourceManager.GetString("failToUpdateMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        internal static string femaleText {
            get {
                return ResourceManager.GetString("femaleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap handle {
            get {
                object obj = ResourceManager.GetObject("handle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        internal static string HighText {
            get {
                return ResourceManager.GetString("HighText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HKD.
        /// </summary>
        internal static string hkdText {
            get {
                return ResourceManager.GetString("hkdText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap home {
            get {
                object obj = ResourceManager.GetObject("home", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your ID or password is incorrect.
        /// </summary>
        internal static string idPasswdIncorrectMsg {
            get {
                return ResourceManager.GetString("idPasswdIncorrectMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input ID.
        /// </summary>
        internal static string inputIdMsg {
            get {
                return ResourceManager.GetString("inputIdMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input ID and password.
        /// </summary>
        internal static string inputIdPasswordMsg {
            get {
                return ResourceManager.GetString("inputIdPasswordMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input security token, new password and confirm password..
        /// </summary>
        internal static string inputPassesTokenMsg {
            get {
                return ResourceManager.GetString("inputPassesTokenMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input valid Email.
        /// </summary>
        internal static string inputValidEmail {
            get {
                return ResourceManager.GetString("inputValidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The invoice is generated in Desktop..
        /// </summary>
        internal static string invoiceGeneratedMsg {
            get {
                return ResourceManager.GetString("invoiceGeneratedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap key {
            get {
                object obj = ResourceManager.GetObject("key", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap login_password {
            get {
                object obj = ResourceManager.GetObject("login_password", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap login_user {
            get {
                object obj = ResourceManager.GetObject("login_user", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logout {
            get {
                object obj = ResourceManager.GetObject("logout", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string logoutText {
            get {
                return ResourceManager.GetString("logoutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        internal static string maleText {
            get {
                return ResourceManager.GetString("maleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager.
        /// </summary>
        internal static string managerText {
            get {
                return ResourceManager.GetString("managerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle.
        /// </summary>
        internal static string MiddleText {
            get {
                return ResourceManager.GetString("MiddleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mL.
        /// </summary>
        internal static string mlText {
            get {
                return ResourceManager.GetString("mlText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        internal static string naText {
            get {
                return ResourceManager.GetString("naText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Order.
        /// </summary>
        internal static string newOrderText {
            get {
                return ResourceManager.GetString("newOrderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The receipt printer is not connected!.
        /// </summary>
        internal static string nonConnectReceiptPrinterMsg {
            get {
                return ResourceManager.GetString("nonConnectReceiptPrinterMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The receipt printer is not selected.
        /// </summary>
        internal static string nonSelectReceiptPrinterMsg {
            get {
                return ResourceManager.GetString("nonSelectReceiptPrinterMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap note {
            get {
                object obj = ResourceManager.GetObject("note", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The order is approved.
        /// </summary>
        internal static string orderApprovalMsg {
            get {
                return ResourceManager.GetString("orderApprovalMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The order is rejected.
        /// </summary>
        internal static string orderRejectMsg {
            get {
                return ResourceManager.GetString("orderRejectMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap package {
            get {
                object obj = ResourceManager.GetObject("package", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package.
        /// </summary>
        internal static string packageText {
            get {
                return ResourceManager.GetString("packageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid.
        /// </summary>
        internal static string paidText {
            get {
                return ResourceManager.GetString("paidText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is changed.
        /// </summary>
        internal static string passwordChangedMsg {
            get {
                return ResourceManager.GetString("passwordChangedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password and confirm password are not match..
        /// </summary>
        internal static string passwordNotMatchMsg {
            get {
                return ResourceManager.GetString("passwordNotMatchMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfume.
        /// </summary>
        internal static string perfumeText {
            get {
                return ResourceManager.GetString("perfumeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The product has been damaged.
        /// </summary>
        internal static string productDamagedText {
            get {
                return ResourceManager.GetString("productDamagedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The product does not match order.
        /// </summary>
        internal static string productNotMatch {
            get {
                return ResourceManager.GetString("productNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap recycle_bin {
            get {
                object obj = ResourceManager.GetObject("recycle_bin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap refund {
            get {
                object obj = ResourceManager.GetObject("refund", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refunded.
        /// </summary>
        internal static string refundedText {
            get {
                return ResourceManager.GetString("refundedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to refund this transition?.
        /// </summary>
        internal static string refundYesNoMsg {
            get {
                return ResourceManager.GetString("refundYesNoMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        internal static string rejectedText {
            get {
                return ResourceManager.GetString("rejectedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject Order.
        /// </summary>
        internal static string rejectOrderText {
            get {
                return ResourceManager.GetString("rejectOrderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap report {
            get {
                object obj = ResourceManager.GetObject("report", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ,
        ///
        ///Hi! Your security token is .
        /// </summary>
        internal static string resetPasswdEmailBodyText1 {
            get {
                return ResourceManager.GetString("resetPasswdEmailBodyText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  . The token will be voided after 5 minutes.
        ///
        ///Thanks,
        ///UNIKA.
        /// </summary>
        internal static string resetPasswdEmailBodyText2 {
            get {
                return ResourceManager.GetString("resetPasswdEmailBodyText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        internal static string resetPasswdEmailSubjectText {
            get {
                return ResourceManager.GetString("resetPasswdEmailSubjectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select account(s).
        /// </summary>
        internal static string selectAccountMsg {
            get {
                return ResourceManager.GetString("selectAccountMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select discount.
        /// </summary>
        internal static string selectDiscountMsg {
            get {
                return ResourceManager.GetString("selectDiscountMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select notice.
        /// </summary>
        internal static string selectNoticeMsg {
            get {
                return ResourceManager.GetString("selectNoticeMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select product.
        /// </summary>
        internal static string selectProductMsg {
            get {
                return ResourceManager.GetString("selectProductMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select receipt printer first.
        /// </summary>
        internal static string selectReceiptPrinterFirstMsg {
            get {
                return ResourceManager.GetString("selectReceiptPrinterFirstMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select receipt printer.
        /// </summary>
        internal static string selectReceiptPrinterMsg {
            get {
                return ResourceManager.GetString("selectReceiptPrinterMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff.
        /// </summary>
        internal static string staffText {
            get {
                return ResourceManager.GetString("staffText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security token is invalid..
        /// </summary>
        internal static string tokenInvalidMsg {
            get {
                return ResourceManager.GetString("tokenInvalidMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The security token is sent to email..
        /// </summary>
        internal static string tokenIsSentMsg {
            get {
                return ResourceManager.GetString("tokenIsSentMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap unika {
            get {
                object obj = ResourceManager.GetObject("unika", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpaid.
        /// </summary>
        internal static string unpaidText {
            get {
                return ResourceManager.GetString("unpaidText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Successfully.
        /// </summary>
        internal static string updateSuccessMsg {
            get {
                return ResourceManager.GetString("updateSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo shound not be greater than 6 MB..
        /// </summary>
        internal static string uploadProblemPhotoErrorMsg {
            get {
                return ResourceManager.GetString("uploadProblemPhotoErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Master.
        /// </summary>
        internal static string webMasterText {
            get {
                return ResourceManager.GetString("webMasterText", resourceCulture);
            }
        }
    }
}
