//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackendForSupplier.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BackendForSupplier.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have attempted to input incorrect password. Your account is lock for 30 minutes..
        /// </summary>
        internal static string accountLock30MinMsg {
            get {
                return ResourceManager.GetString("accountLock30MinMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is locked. Please login again later..
        /// </summary>
        internal static string accountLockedMsg {
            get {
                return ResourceManager.GetString("accountLockedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is not activated..
        /// </summary>
        internal static string accountNotActivatedMsg {
            get {
                return ResourceManager.GetString("accountNotActivatedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to add new product..
        /// </summary>
        internal static string addNewProductFailMsg {
            get {
                return ResourceManager.GetString("addNewProductFailMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new product successfully.
        /// </summary>
        internal static string addNewProductSuccessMsg {
            get {
                return ResourceManager.GetString("addNewProductSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap alert {
            get {
                object obj = ResourceManager.GetObject("alert", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string allText {
            get {
                return ResourceManager.GetString("allText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to logout the System?.
        /// </summary>
        internal static string askLogoutDialogbox {
            get {
                return ResourceManager.GetString("askLogoutDialogbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention.
        /// </summary>
        internal static string attentionText {
            get {
                return ResourceManager.GetString("attentionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bottle {
            get {
                object obj = ResourceManager.GetObject("bottle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottle.
        /// </summary>
        internal static string bottleText {
            get {
                return ResourceManager.GetString("bottleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Photo.
        /// </summary>
        internal static string choosePhotoText {
            get {
                return ResourceManager.GetString("choosePhotoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted product(s) has/have been recovered..
        /// </summary>
        internal static string deletedProcuctRecoverMsg {
            get {
                return ResourceManager.GetString("deletedProcuctRecoverMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The product(s) has/have been deleted..
        /// </summary>
        internal static string deleteMsg {
            get {
                return ResourceManager.GetString("deleteMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The product(s) has/have been deleted permanently..
        /// </summary>
        internal static string deletePermanentlyMsg {
            get {
                return ResourceManager.GetString("deletePermanentlyMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you delete product(s) permanently?.
        /// </summary>
        internal static string deletePermanentlyYesNoMsg {
            get {
                return ResourceManager.GetString("deletePermanentlyYesNoMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string deleteTitle {
            get {
                return ResourceManager.GetString("deleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you delete product(s)?.
        /// </summary>
        internal static string deleteYesNoMsg {
            get {
                return ResourceManager.GetString("deleteYesNoMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string errorText {
            get {
                return ResourceManager.GetString("errorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to change password..
        /// </summary>
        internal static string failToChangePasswdMsg {
            get {
                return ResourceManager.GetString("failToChangePasswdMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send email.
        /// </summary>
        internal static string failToSendMailMsg {
            get {
                return ResourceManager.GetString("failToSendMailMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill all in text box..
        /// </summary>
        internal static string fillAllMsg {
            get {
                return ResourceManager.GetString("fillAllMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill all text box, select category and upload photo..
        /// </summary>
        internal static string fillAllWithCategoryPhotoMsg {
            get {
                return ResourceManager.GetString("fillAllWithCategoryPhotoMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill all text box and upload photo..
        /// </summary>
        internal static string fillAllWithPhotoMsg {
            get {
                return ResourceManager.GetString("fillAllWithPhotoMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HKD.
        /// </summary>
        internal static string hkdText {
            get {
                return ResourceManager.GetString("hkdText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap home {
            get {
                object obj = ResourceManager.GetObject("home", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your ID or password is incorrect.
        /// </summary>
        internal static string idPasswdIncorrectMsg {
            get {
                return ResourceManager.GetString("idPasswdIncorrectMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input Capacity 1 or over..
        /// </summary>
        internal static string inputCapacity1OverMsg {
            get {
                return ResourceManager.GetString("inputCapacity1OverMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input ID and password.
        /// </summary>
        internal static string inputIdPasswordMsg {
            get {
                return ResourceManager.GetString("inputIdPasswordMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password is incorrect..
        /// </summary>
        internal static string inputIncorrectCurrentPasswdMsg {
            get {
                return ResourceManager.GetString("inputIncorrectCurrentPasswdMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input price 1 to 300.
        /// </summary>
        internal static string inputPrice1To300Msg {
            get {
                return ResourceManager.GetString("inputPrice1To300Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input Quantity in Stock 50 or over.
        /// </summary>
        internal static string inputQtyOver50Msg {
            get {
                return ResourceManager.GetString("inputQtyOver50Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap key {
            get {
                object obj = ResourceManager.GetObject("key", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap login_password {
            get {
                object obj = ResourceManager.GetObject("login_password", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap login_user {
            get {
                object obj = ResourceManager.GetObject("login_user", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logout {
            get {
                object obj = ResourceManager.GetObject("logout", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string logoutText {
            get {
                return ResourceManager.GetString("logoutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mL.
        /// </summary>
        internal static string mlText {
            get {
                return ResourceManager.GetString("mlText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap package {
            get {
                object obj = ResourceManager.GetObject("package", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package.
        /// </summary>
        internal static string packageText {
            get {
                return ResourceManager.GetString("packageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is changed.
        /// </summary>
        internal static string passwordChangedMsg {
            get {
                return ResourceManager.GetString("passwordChangedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfume.
        /// </summary>
        internal static string perfumeText {
            get {
                return ResourceManager.GetString("perfumeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap recycle_bin {
            get {
                object obj = ResourceManager.GetObject("recycle_bin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted product(s) was/were stored temporarily in recycle bin over 1 year ago, please delete below produc(s) permanently as soon as possible:.
        /// </summary>
        internal static string recycleBinAlertMsg {
            get {
                return ResourceManager.GetString("recycleBinAlertMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recycle Bin Alert.
        /// </summary>
        internal static string recycleBinAlertTitle {
            get {
                return ResourceManager.GetString("recycleBinAlertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rerfume {
            get {
                object obj = ResourceManager.GetObject("rerfume", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ,
        ///
        ///Hi! Your security token is .
        /// </summary>
        internal static string resetPasswdEmailBodyText1 {
            get {
                return ResourceManager.GetString("resetPasswdEmailBodyText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  . The token will be voided after 5 minutes.
        ///
        ///Thanks,
        ///UNIKA.
        /// </summary>
        internal static string resetPasswdEmailBodyText2 {
            get {
                return ResourceManager.GetString("resetPasswdEmailBodyText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        internal static string resetPasswdEmailSubjectText {
            get {
                return ResourceManager.GetString("resetPasswdEmailSubjectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Category.
        /// </summary>
        internal static string selectCategoryMsg {
            get {
                return ResourceManager.GetString("selectCategoryMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select deleted product..
        /// </summary>
        internal static string selectProcuctDeletedMsg {
            get {
                return ResourceManager.GetString("selectProcuctDeletedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select product.
        /// </summary>
        internal static string selectProcuctMsg {
            get {
                return ResourceManager.GetString("selectProcuctMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The quantity of products are below 50, please replenish stock as soon as possible:.
        /// </summary>
        internal static string stockAlertMsg {
            get {
                return ResourceManager.GetString("stockAlertMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The products are out of stock, please replenish stock as soon as possible:.
        /// </summary>
        internal static string stockAlertNoItemMsg {
            get {
                return ResourceManager.GetString("stockAlertNoItemMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Alert.
        /// </summary>
        internal static string stockAlertTitle {
            get {
                return ResourceManager.GetString("stockAlertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The security token is sent to email..
        /// </summary>
        internal static string tokenIsSentMsg {
            get {
                return ResourceManager.GetString("tokenIsSentMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap unika {
            get {
                object obj = ResourceManager.GetObject("unika", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update the product..
        /// </summary>
        internal static string updateProductFailMsg {
            get {
                return ResourceManager.GetString("updateProductFailMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update the product successfully.
        /// </summary>
        internal static string updateProductSuccessMsg {
            get {
                return ResourceManager.GetString("updateProductSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo shound be 512 × 512 pixels and not be greater than 1 MB..
        /// </summary>
        internal static string uploadPhotoErrorMsg {
            get {
                return ResourceManager.GetString("uploadPhotoErrorMsg", resourceCulture);
            }
        }
    }
}
