//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessClassLibrary.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataAccessClassLibrary.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account is unloacked by .
        /// </summary>
        internal static string accountUnlockLog1 {
            get {
                return ResourceManager.GetString("accountUnlockLog1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string accountUnlockLog2 {
            get {
                return ResourceManager.GetString("accountUnlockLog2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input incorrect password for 5 times. The account is lock for 30 minutes..
        /// </summary>
        internal static string inputIncorrectPasswd5TimesLog {
            get {
                return ResourceManager.GetString("inputIncorrectPasswd5TimesLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input incorrect password.
        /// </summary>
        internal static string inputIncorrectPasswdLog {
            get {
                return ResourceManager.GetString("inputIncorrectPasswdLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to login while the account is locked..
        /// </summary>
        internal static string loginAccountWhileLockedLog {
            get {
                return ResourceManager.GetString("loginAccountWhileLockedLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login success.
        /// </summary>
        internal static string loginSuccessLog {
            get {
                return ResourceManager.GetString("loginSuccessLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login success without verified email..
        /// </summary>
        internal static string loginSuccessWithoutVerifiedEmailLog {
            get {
                return ResourceManager.GetString("loginSuccessWithoutVerifiedEmailLog", resourceCulture);
            }
        }
    }
}
